services:
  runner:
    image: ghcr.io/js2702/self-hosted-runner:main
    restart: always
    environment:
      - REPO=${REPO:?set REPO}
      - REG_TOKEN=${REG_TOKEN:?set REG_TOKEN}
      - NAME=${NAME:-self-hosted-runner}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
